import { notFound } from "next/navigation";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import GalleryGrid from "@/components/GalleryGrid";
import AISummaryCard from "@/components/AISummaryCard";
import { Building, MapPin, Calendar, User, Home, Sparkles, Globe, Share2, Download } from "lucide-react";

interface PreviewPageProps {
  params: Promise<{ id: string }>;
}

async function getListingData(id: string) {
  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001"}/api/process/zip/${id}`,
      { cache: "no-store" }
    );
    
    if (!response.ok) {
      if (response.status === 404) {
        return null;
      }
      throw new Error(`Failed to fetch listing: ${response.statusText}`);
    }
    
    const contentType = response.headers.get("content-type");
    if (!contentType || !contentType.includes("application/json")) {
      console.error("Response is not JSON:", contentType);
      return null;
    }
    
    return await response.json();
  } catch (error) {
    console.error("Error fetching listing data:", error);
    return null;
  }
}

export default async function PreviewPage({ params }: PreviewPageProps) {
  const { id } = await params;
  const data = await getListingData(id);

  if (!data) {
    notFound();
  }

  const listing = data.listing || {};
  const media = data.media || [];
  const aiResults = data.aiResults || null;

  // Transform media data for GalleryGrid
  const transformedMedia = media.map((item: any) => ({
    id: item.id,
    url: item.url,
    category: item.category || "UNKNOWN",
    aiTags: item.aiTags || [],
    aiSaliencyScore: item.aiSaliencyScore,
    isFeatured: item.isFeatured || false,
    processingStatus: item.processingStatus || "DONE",
  }));

  // Transform AI results for AISummaryCard
  const transformedAIResults = aiResults ? {
    headline: aiResults.headline || "AI Generated Headline",
    shortDesc: aiResults.shortDesc || "AI generated short description based on property analysis.",
    longDesc: aiResults.longDesc || "AI generated long description with detailed property analysis.",
    bulletPoints: aiResults.bulletPoints || [],
    seoTitle: aiResults.seoTitle || "SEO Optimized Title",
    seoDescription: aiResults.seoDescription || "SEO optimized description for better search visibility.",
    priceSuggestion: aiResults.priceSuggestion || 8500000,
    targetAudience: aiResults.targetAudience || "Young couples, families with children",
  } : null;

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
      {/* Preview header */}
      <div className="bg-gradient-to-r from-primary/10 via-primary/5 to-transparent border-b border-primary/20">
        <div className="container mx-auto px-4 py-6">
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-xl bg-gradient-to-br from-primary to-primary/80 shadow-lg">
                <Globe className="h-8 w-8 text-white" />
              </div>
              <div>
                <h1 className="text-3xl font-bold font-sans tracking-tight">
                  {listing.title || "Property Listing"} - Preview
                </h1>
                <div className="flex items-center gap-3 mt-2">
                  <Badge className="bg-gradient-to-r from-green-500 to-green-600 text-white border-0 px-3 py-1 font-sans tracking-tight">
                    <Sparkles className="h-3.5 w-3.5 mr-1.5" />
                    AI-Powered Preview
                  </Badge>
                  <Badge variant="outline" className="font-sans tracking-tight">
                    ID: {id.slice(0, 8)}
                  </Badge>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <Badge variant="outline" className="font-sans tracking-tight">
                <Share2 className="h-3.5 w-3.5 mr-1.5" />
                Preview Mode
              </Badge>
              <div className="text-sm text-muted-foreground font-sans tracking-tight">
                Generated by REALFORGE AI
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main preview content */}
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left column: Property details and gallery */}
          <div className="lg:col-span-2 space-y-8">
            {/* Property overview */}
            <Card className="border-2 border-primary/20 bg-gradient-to-br from-white/50 to-transparent">
              <CardHeader>
                <CardTitle className="text-2xl font-bold font-sans tracking-tight flex items-center gap-3">
                  <Home className="h-6 w-6 text-primary" />
                  Property Overview
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div className="flex items-center gap-3">
                      <MapPin className="h-5 w-5 text-primary" />
                      <div>
                        <div className="text-sm text-muted-foreground font-sans tracking-tight">Location</div>
                        <div className="font-medium font-sans tracking-tight">{listing.location || listing.address || "Prague, Czech Republic"}</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <Building className="h-5 w-5 text-primary" />
                      <div>
                        <div className="text-sm text-muted-foreground font-sans tracking-tight">Type</div>
                        <div className="font-medium font-sans tracking-tight">{listing.propertyType || listing.type || "Apartment"}</div>
                      </div>
                    </div>
                  </div>
                  <div className="space-y-4">
                    <div className="flex items-center gap-3">
                      <Calendar className="h-5 w-5 text-primary" />
                      <div>
                        <div className="text-sm text-muted-foreground font-sans tracking-tight">Listed</div>
                        <div className="font-medium font-sans tracking-tight">
                          {listing.createdAt ? new Date(listing.createdAt).toLocaleDateString("cs-CZ") : "Recently"}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <User className="h-5 w-5 text-primary" />
                      <div>
                        <div className="text-sm text-muted-foreground font-sans tracking-tight">Status</div>
                        <div className="font-medium font-sans tracking-tight">
                          <Badge className="bg-green-500 text-white border-0 font-sans tracking-tight">
                            {listing.status === "COMPLETED" ? "Ready" : "Available"}
                          </Badge>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                
                {/* Price section */}
                <div className="mt-6 pt-6 border-t border-primary/20">
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="text-sm text-muted-foreground font-sans tracking-tight">Asking Price</div>
                      <div className="text-3xl font-bold text-primary font-sans tracking-tight">
                        {listing.price ? `${listing.price.toLocaleString('cs-CZ')} CZK` : "Price upon request"}
                      </div>
                    </div>
                    {aiResults?.priceSuggestion && (
                      <div className="text-right">
                        <div className="text-sm text-muted-foreground font-sans tracking-tight">AI Suggested Price</div>
                        <div className="text-xl font-bold text-green-600 font-sans tracking-tight">
                          {aiResults.priceSuggestion.toLocaleString('cs-CZ')} CZK
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Photo gallery */}
            <Card className="border-2 border-primary/20 bg-gradient-to-br from-white/50 to-transparent">
              <CardHeader>
                <CardTitle className="text-2xl font-bold font-sans tracking-tight flex items-center gap-3">
                  <Sparkles className="h-6 w-6 text-primary" />
                  Photo Gallery
                </CardTitle>
                <CardDescription className="font-sans tracking-tight">
                  {transformedMedia.length} professionally photographed images
                </CardDescription>
              </CardHeader>
              <CardContent>
                <GalleryGrid media={transformedMedia} compact={true} />
              </CardContent>
            </Card>
          </div>

          {/* Right column: AI content and actions */}
          <div className="space-y-8">
            {/* AI Generated Content */}
            <Card className="border-2 border-primary/20 bg-gradient-to-br from-white/50 to-transparent">
              <CardHeader>
                <CardTitle className="text-2xl font-bold font-sans tracking-tight">AI Generated Description</CardTitle>
                <CardDescription className="font-sans tracking-tight">
                  Professionally written property description
                </CardDescription>
              </CardHeader>
              <CardContent>
                <AISummaryCard 
                  aiResults={transformedAIResults} 
                  confidenceScore={aiResults?.aiSaliencyScore ? Math.round(aiResults.aiSaliencyScore * 100) : 85}
                  compact={true}
                />
              </CardContent>
            </Card>

            {/* Call to action */}
            <Card className="border-2 border-green-500/20 bg-gradient-to-br from-green-50 to-transparent">
              <CardHeader>
                <CardTitle className="text-2xl font-bold text-green-700 font-sans tracking-tight flex items-center gap-3">
                  <Download className="h-6 w-6 text-green-600" />
                  Ready to Publish?
                </CardTitle>
                <CardDescription className="font-sans tracking-tight">
                  This preview is ready for your website or real estate platforms
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="text-sm text-muted-foreground font-sans tracking-tight">
                    This AI-optimized listing includes:
                  </div>
                  <ul className="space-y-2 text-sm font-sans tracking-tight">
                    <li className="flex items-center gap-2">
                      <div className="h-2 w-2 rounded-full bg-green-500"></div>
                      Professional property description
                    </li>
                    <li className="flex items-center gap-2">
                      <div className="h-2 w-2 rounded-full bg-green-500"></div>
                      SEO-optimized titles and meta descriptions
                    </li>
                    <li className="flex items-center gap-2">
                      <div className="h-2 w-2 rounded-full bg-green-500"></div>
                      High-quality categorized photos
                    </li>
                    <li className="flex items-center gap-2">
                      <div className="h-2 w-2 rounded-full bg-green-500"></div>
                      Market analysis and price suggestion
                    </li>
                  </ul>
                  <div className="pt-4 border-t border-green-500/20">
                    <div className="text-sm font-sans tracking-tight">
                      <strong>Next steps:</strong> Use the Export & Share buttons in the main listing to publish this property.
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Preview info */}
            <Card className="border-2 border-primary/10">
              <CardContent className="p-6">
                <div className="text-center">
                  <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary font-sans tracking-tight">
                    <Sparkles className="h-4 w-4" />
                    AI-Powered Preview
                  </div>
                  <p className="mt-4 text-sm text-muted-foreground font-sans tracking-tight">
                    This is a preview generated by REALFORGE AI. All content is automatically created based on property analysis.
                  </p>
                  <div className="mt-4 text-xs text-muted-foreground font-sans tracking-tight">
                    Listing ID: {id}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-primary/20">
          <div className="text-center">
            <div className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-primary/10 to-primary/5 border border-primary/20">
              <Sparkles className="h-5 w-5 text-primary" />
              <span className="font-bold text-primary font-sans tracking-tight">REALFORGE AI</span>
              <span className="text-muted-foreground font-sans tracking-tight">• Premium Real Estate Marketing</span>
            </div>
            <p className="mt-4 text-sm text-muted-foreground font-sans tracking-tight">
              This preview was automatically generated by AI. For the full experience with export options, 
              visit the main listing page.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}